application: selfcommit-hello
module: rando
version: 1
runtime: python27
api_version: 1
threadsafe: true

# https://cloud.google.com/appengine/docs/python/tools/libraries27?hl=en
libraries:
- name: webapp2
  version: "latest"

handlers:
- url: .*
  script: main.app